language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

install: composer install

script:
  - vendor/bin/phpunit tests

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: nightly
